name: Store commit hash

on:
  push:
    paths-ignore:
      - commit.txt

jobs:
  store-commit-hash:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            commit.txt
            !*.png
            !*.jpg
            !*.jpeg
            !*.gif
            .
          sparse-checkout-cone-mode: false
          fetch-depth: 1

      - name: Fetch commit hash
        id: get_commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Write file
        run: |
          echo "${{ steps.get_commit.outputs.hash }}" > commit.txt
          if git diff --quiet commit.txt; then
            echo "No changes to commit.txt"
            exit 0
          fi
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add commit.txt
          if git log -1 --pretty=%an | grep -q "github-actions"; then
            git commit --amend --no-edit
          else
            git commit -m "Update commit hash"
          fi
          git push --force